Name:           ros-kinetic-octomap-rviz-plugins
Version:        0.1.0
Release:        0%{?dist}
Summary:        ROS octomap_rviz_plugins package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/octomap_rviz_plugins
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-octomap
Requires:       ros-kinetic-octomap-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rviz
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-octomap
BuildRequires:  ros-kinetic-octomap-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rviz

%description
A set of plugins for displaying occupancy information decoded from binary
octomap messages.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Jul 07 2016 Armin Hornung <armin@hornung.io> - 0.1.0-0
- Autogenerated by Bloom

